### ISSUE TITLE
Synchronize fails if resource column is None

### ISSUE THREAD

**Issue by kokorin** [kokorin/dbt-pumpkin#37]
The following fails:

```yaml:
models:
  - name: my_model
    columns: null
```

But this works:

```yaml:
models:
  - name: my_model
    columns: []
```
