### ISSUE TITLE
Allow non-root-relative paths for Source Resoruces

### ISSUE THREAD

**Issue by kokorin** [kokorin/dbt-pumpkin#50]
Sources require root-relative path to be used for `dbt-pumpkin-path` conf property.
The actual limitation is less strict: source YAML path should be idempotent. For that it's enough to validate that target YAML path is sibling to the original YAML path.

Example:
```yml
# sources.yml
version: 2
sources:
  - name: my_source
    tables: [ ... ]
  - name: my_another_source
    tables: [ ... ]
```

```yml
# dbt_project.yml
...
sources:
  +dbt-pumpking-path: "_source_{name}.yml"
```

Expected files:

```yml
# _source_my_source.yml
version: 2
sources:
  - name: my_source
    tables: [ ... ]
```

```yml
# _source_my_another_source.yml
version: 2
sources:
  - name: my_another_source
    tables: [ ... ]
```

This allows to make sure that target file path doesn't depend on previous invocations and is definitely defined.
