### ISSUE TITLE
Rename variable yaml to yaml_format

### ISSUE THREAD

**Issue by kokorin** [kokorin/dbt-pumpkin#57]
Support backward compatibility with warning.

Before:
```yaml
vars:
  dbt-pumpkin:
    yaml:
      ...
```

After
```yaml
vars:
  dbt-pumpkin:
    yaml_format:
      ...
```
